# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: "Chicago" }, { name: "Copenhagen" }])
#   Mayor.create(name: "Emanuel", city: cities.first)

Person.create(firstname: "Matt", lastname: "Briggs", username: "MB", email: "mattbriggs@yahoo.com", mobile: "027 2010304", homephone: "03 4490000", address1: "67 Perseverence Dr", address2: "Bridge Hill", address3: "Alexandra", postcode: "9320", is_member: true, is_active: true, is_source: false, is_destination: false, is_admin: true,  is_user: true, is_modifier: true, password: "dummy", password_confirmation: "dummy")

Projection.create(id: 2193, name: "NZTM2000", proj4: "+proj=tmerc +lat_0=0 +lon_0=173 +k=0.9996 +x_0=1600000 +y_0=10000000 +ellps=GRS80 +towg", wkt: "", epsg: 2193)
Projection.create(id: 4326, name: "WGS84", proj4: "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs", wkt: "", epsg: 4326)
Projection.create(id: 27200, name: "NZMG49", proj4: "+proj=nzmg +lat_0=-41 +lon_0=173 +x_0=2510000 +y_0=6023150 +ellps=intl +datum=nzgd49 +units=m +no_defs", wkt: "", epsg: 27200)
Projection.create(id: 27291, name: "NIYG", proj4: "+proj=tmerc +lat_0=-39 +lon_0=175.5 +k=1 +x_0=274319.5243848086 +y_0=365759.3658464114 +ellps=intl +datum=nzgd49 +to_meter=0.9143984146160287 +no_defs", wkt: "", epsg: 27291)
Projection.create(id: 27292, name: "SIYG", proj4: "+proj=tmerc +lat_0=-44 +lon_0=171.5 +k=1 +x_0=457199.2073080143 +y_0=457199.2073080143 +ellps=intl +datum=nzgd49 +to_meter=0.9143984146160287 +no_defs", wkt: "", epsg: 27292)
Projection.create(id: 900913, name: "GOOGLE", proj4: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +no_defs", wkt: "", epsg: 900913)

#ThreatQualifier.create(name: "Conservation Dependent", code: "CD")
#ThreatQualifier.create(name: "Data Poor", code: "DP")
#ThreatQualifier.create(name: "Extreme Fluctuations", code: "EF")
#ThreatQualifier.create(name: "Extinct in the Wild", code: "EW")
#ThreatQualifier.create(name: "One Location", code: "OL")
#ThreatQualifier.create(name: "Recruitment Failure", code: "RF")
#ThreatQualifier.create(name: "Secure Overseas", code: "SO")
#ThreatQualifier.create(name: "Threatened Overseas", code: "TO")
#ThreatQualifier.create(name: "Stable", code: "St")
#ThreatQualifier.create(name: "Designated", code: "De")
#ThreatQualifier.create(name: "Island Endemic", code: "IE")
#ThreatQualifier.create(name: "Increasing", code: "Inc")
#ThreatQualifier.create(name: "Partial Decline", code: "PD")
#ThreatQualifier.create(name: "Range Restricted", code: "RR")
#ThreatQualifier.create(name: "Sparse", code: "Sp")

Species.create(code: "AciAur", genus:"Aciphylla", species: "aurea", common_name: "taramea", is_active: true)
Species.create(code: "AciGla", genus: "Aciphylla", species: "glaucescens", common_name: "feathery Spaniard", is_active: true)
Species.create(code: "AriFru", genus: "Aristotelia", species: "fruticosa", common_name: "mountain wineberry", is_active: true)
Species.create(code: "AusRic", genus: "Austroderia", species: "richardii", common_name: "toetoe", is_active: true)
Species.create(code: "CarSec", genus: "Carex", species: "secta", common_name: "purei/sedge", is_active: true)
Species.create(code: "CarCom", genus: "Carmichaelia", species: "compacta", common_name: "Cromwell broom", is_active: true)
Species.create(code: "CarCra", genus: "Carmichaelia", species: "crassicaulis ssp crassicaulis", common_name: "coral broom", is_active: true)
Species.create(code: "CarPet", genus: "Carmichaelia", species: "petriei", common_name: "desert broom", is_active: true)
Species.create(code: "CleQua", genus: "Clematis", species: "quadribracteolata", common_name: "", is_active: true)
Species.create(code: "CopChe", genus: "Coprosma", species: "chessemanii", common_name: "", is_active: true)
Species.create(code: "CopDum", genus: "Coprosma", species: "dumosa", common_name: "", is_active: true)
Species.create(code: "CopPro", genus: "Coprosma", species: "propinqua", common_name: "mikimiki", is_active: true)
Species.create(code: "CopRug", genus: "Coprosma", species: "rugosa", common_name: "", is_active: true)
Species.create(code: "CorAus", genus: "Cordyline", species: "australis", common_name: "ti kouka", is_active: true)
Species.create(code: "CorCot", genus: "Corokia", species: "cotoneaster", common_name: "korokio", is_active: true)
Species.create(code: "DisTou", genus: "Discaria", species: "toumatou", common_name: "matagouri", is_active: true)
Species.create(code: "HelLan", genus: "Helichrysum", species: "lanceolatum", common_name: "niniao", is_active: true)
Species.create(code: "HohLya", genus: "Hoheria", species: "lyalli", common_name: "mountain ribbonwood", is_active: true)
Species.create(code: "KunRob", genus: "Kunzea", species: "robusta", common_name: "kanuka", is_active: true)
Species.create(code: "KunSer", genus: "Kunzea", species: "serotina", common_name: "kanuka", is_active: true)
Species.create(code: "LepSco", genus: "Leptospermum", species: "scoparium", common_name: "manuka", is_active: true)
Species.create(code: "MelAlp", genus: "Melicytus", species: "alpinus", common_name: "porcupine bush", is_active: true)
Species.create(code: "MelSim", genus: "Melicope", species: "simplex", common_name: "poataniwha", is_active: true)
Species.create(code: "MueAus", genus: "Muehlenbeckia", species: "australis x complexa", common_name: "pohuehue/wire vine", is_active: true)
Species.create(code: "MueCom", genus: "Muehlenbeckia", species: "complexa", common_name: "pohuehue/wire vine", is_active: true)
Species.create(code: "OleAvi", genus: "Olearia", species: "avicenniifolia", common_name: "", is_active: true)
Species.create(code: "OleHec", genus: "Olearia", species: "hectorii", common_name: "Hector's tree daisy", is_active: true)
Species.create(code: "OleLin", genus: "Olearia", species: "lineata", common_name: "tree daisy", is_active: true)
Species.create(code: "OleOdo", genus: "Olearia", species: "odorata", common_name: "scented tree daisy", is_active: true)
Species.create(code: "OzoVau", genus: "Ozothamnus", species: "vauvilliersii", common_name: "mountain tauhinu", is_active: true)
Species.create(code: "PhoCoo", genus: "Phormium", species: "cookianum", common_name: "wharariki/mountain flax", is_active: true)
Species.create(code: "PhoTen", genus: "Phormium", species: "tenax", common_name: "harakeke", is_active: true)
Species.create(code: "PimAri", genus: "Pimelea", species: "aridula", common_name: "native daphne", is_active: true)
Species.create(code: "PitTen", genus: "Pittosporum", species: "tenuifolium", common_name: "rautawhiri/köhütü", is_active: true)
Species.create(code: "PlaReg", genus: "Plagianthus", species: "regius", common_name: "ribbonwood", is_active: true)
Species.create(code: "SopMic", genus: "Sophora", species: "microphylla", common_name: "kowhai", is_active: true)
Species.create(code: "VerCup", genus: "Veronica", species: "cupressoides", common_name: "cypress hebe", is_active: true)
Species.create(code: "VerPim", genus: "Veronica", species: "pimeleoides ssp faucicola", common_name: "hebe/pimelia", is_active: true)
Species.create(code: "VerSal", genus: "Veronica", species: "salicifolia", common_name: "koromiko", is_active: true, is_active: true)
Species.create(code: "RaoAus", genus:"Raoulia", species: "australis", common_name: "golden scabweed", is_active: true)
Species.create(code: "MyrDiv", genus:"Myrsine", species: "divaricata", common_name: "weeping mapou", is_active: true)
Species.create(code: "OleFim", genus:"Olearia", species: "fimbriata", common_name: "", is_active: true)
Species.create(code: "OleFra", genus:"Olearia", species: "fragrantissima", common_name: "fragrant tree daisy ", is_active: true)
Species.create(code: "PodNiv", genus:"Podocarpus", species: "nivalis", common_name: "snow totara", is_active: true) 
Species.create(code: "PodLae", genus:"Podocarpus", species: "laetus", common_name: "Hall's Totara", is_active: true) 
Species.create(code: "HalBid", genus:"Halocarpus", species: "bidwilli", common_name: "bog pine", is_active: true) 
Species.create(code: "PhyAlp", genus:"Phyllocladus", species: "alpinus", common_name: "celery pine", is_active: true) 
Species.create(code: "LopMen", genus:"Lophozonia", species: "menzeisii", common_name: "silver beech", is_active: true) 
Species.create(code: "CleMar", genus:"Clematis", species: "marata", common_name: "Clematis", is_active: true) 
Species.create(code: "ParCap", genus:"Parsonsia", species: "capsularis", common_name: "NZ Jasmine", is_active: true) 


Maplayer.create(name: "NZTM Topo 2009", baseurl: "http://au.mapspast.org.nz/topo50/", basemap: "mapspast", minzoom: 0, maxzoom: 10, imagetype: "png")
Maplayer.create(name: "(LINZ) Topo50 latest", baseurl: "http://tiles-a.data-cdn.linz.govt.nz/services;key=d8c83efc690a4de4ab067eadb6ae95e4/tiles/v4/layer=767/EPSG:2193/", basemap: "linz", minzoom: 0, maxzoom: 16, imagetype: "png")
Maplayer.create(name: "(LINZ) Airphoto latest", baseurl: "http://tiles-a.data-cdn.linz.govt.nz/services;key=d8c83efc690a4de4ab067eadb6ae95e4/tiles/v4/set=2/EPSG:2193/", basemap: "linz", minzoom: 0, maxzoom: 16, imagetype: "png")

Source.create(id: 1, name: "249 ChapmanRoad", notes: "Roger&WendyBrowne", is_active: true)
Source.create(id: 2, name: "Alex airport", notes: "CODC", is_active: true)
Source.create(id: 3, name: "Bendigo", notes: "DOC", is_active: true)
Source.create(id: 4, name: "ClydeBridge", notes: "ProjectGold", is_active: true)
Source.create(id: 5, name: "Northburn Station", notes: "", is_active: true)
Source.create(id: 6, name: "Omeo", notes: "Campbell", is_active: true)
Source.create(id: 7, name: "Pukerau", notes: "IanSmith", is_active: true)
Source.create(id: 8, name: "Robertson'sCreek", notes: "LINZ?", is_active: true)
Source.create(id: 9, name: "RoxburghGorge", notes: "IanSmith", is_active: true)
Source.create(id: 10, name: "Saunders", notes: "Saunders", is_active: true)
Source.create(id: 11, name: "ShingleCreek", notes: "Contact?", is_active: true)
Source.create(id: 12, name: "TreestoneFar", notes: "Bill&Corinne", is_active: true)
Source.create(id: 13, name: "WaikeriDownsWest", notes: "Earl&BernieAttfield", is_active: true)
Source.create(id: 14, name: "WaikerikeriValleyStn", notes: "Richard&JacquiParsons", is_active: true)
Source.create(id: 15, name: "Blackstone Hill", notes: "DOC", is_active: true)
Source.create(id: 16, name: "Chasm Creek", notes: "", is_active: true)


Collection.create(id: -100, source_id: nil, date: "01/01/2000", source_description: "Roxburgh Gorge", species_code: "", x: nil, y: nil, altitude: nil, no_plants_sampled: nil, notes: " - Also:", team_members: "", projection_id: 2193, is_seeds: true, is_cuttings: false)
Collection.create(id: -99, source_id: nil, date: "2/03/2017", source_description: "Motutapu", species_code: "CopDum", x: 1278741, y: 5040358, altitude: nil, no_plants_sampled: 20, notes: " - Also:AriFru,DisTou,CopPro, CopRug, LepSco", team_members: "DP,TW", projection_id: 2193, is_seeds: true, is_cuttings: false)
Collection.create(id: -98, source_id: nil, date: "2/03/2017", source_description: "Motutapu", species_code: "AriFru", x: 1278741, y: 5040358, altitude: nil, no_plants_sampled: 5, notes: " - Also:", team_members: "DP,TW", projection_id: 2193, is_seeds: true, is_cuttings: false)
Collection.create(id: -97, source_id: nil, date: "2/03/2017", source_description: "Motutapu", species_code: "CopRug", x: 1278741, y: 5040358, altitude: nil, no_plants_sampled: 20, notes: " - Also:", team_members: "DP,TW", projection_id: 2193, is_seeds: true, is_cuttings: false)
Collection.create(id: -96, source_id: 10, date: "8/03/2017", source_description: "Graveyard Gully", species_code: "CopPro", x: nil, y: nil, altitude: nil, no_plants_sampled: nil, notes: " - Also:", team_members: "Teachers", projection_id: 2193, is_seeds: true, is_cuttings: false)
Collection.create(id: -95, source_id: 10, date: "8/03/2017", source_description: "Graveyard Gully", species_code: "OleOdo", x: nil, y: nil, altitude: nil, no_plants_sampled: nil, notes: " - Also:", team_members: "Teachers", projection_id: 2193, is_seeds: true, is_cuttings: false)
Collection.create(id: -94, source_id: nil, date: "18/03/2017", source_description: "Earls", species_code: "SopMic", x: nil, y: nil, altitude: nil, no_plants_sampled: nil, notes: "small clump - Also:", team_members: "WN", projection_id: 2193, is_seeds: true, is_cuttings: false)
Collection.create(id: -93, source_id: nil, date: "25/03/2017", source_description: "El Pedregal", species_code: "CorCot", x: nil, y: nil, altitude: nil, no_plants_sampled: 9, notes: "sunny face all the same - Also:", team_members: "WN", projection_id: 2193, is_seeds: true, is_cuttings: false)
Collection.create(id: -92, source_id: nil , date: "25/03/2017", source_description: "El Pedregal", species_code: "CorCot", x: 1308486, y: 4986250, altitude: nil, no_plants_sampled: nil, notes: " - Also:", team_members: "WN", projection_id: 2193, is_seeds: true, is_cuttings: false)
Collection.create(id: -91, source_id: nil, date: "25/03/2017", source_description: "El Ped side Dunstan Hills", species_code: "CorCot", x: nil, y: nil, altitude: nil, no_plants_sampled: 5, notes: "orange/yellow - Also:", team_members: "WN", projection_id: 2193, is_seeds: true, is_cuttings: false)
Collection.create(id: -90, source_id: nil, date: "30/03/2017", source_description: "Motutapu", species_code: "HohLya", x: 1273669, y: 5032987, altitude: 648, no_plants_sampled: 2, notes: " - Also:", team_members: "DP, TW", projection_id: 2193, is_seeds: true, is_cuttings: false)
Collection.create(id: -89, source_id: nil, date: "30/03/2017", source_description: "Motutapu", species_code: "CopChe", x: 1273668, y: 5032986, altitude: 648, no_plants_sampled: 1, notes: " - Also:CopPro,CopDum,Gaultheria,DraLon, FusCli", team_members: "DP, TW", projection_id: 2193, is_seeds: true, is_cuttings: false)
Collection.create(id: -88, source_id: 5, date: "1/04/2017", source_description: "Champagne Gully", species_code: "MelSim", x: 1310634, y: 4996168, altitude: 279, no_plants_sampled: 0, notes: " - Also:", team_members: "WG,DP,ID, RM", projection_id: 2193, is_seeds: true, is_cuttings: false)
Collection.create(id: -87, source_id: nil, date: "1/04/2017", source_description: "", species_code: "MelAlp", x: 1311472, y: 4996431, altitude: 360, no_plants_sampled: nil, notes: " - Also:", team_members: "WG,DP,ID, RM", projection_id: 2193, is_seeds: true, is_cuttings: false)
Collection.create(id: -86, source_id: nil, date: "1/04/2017", source_description: "Champagne Gully", species_code: "CopPro", x: 1311553, y: 4996222, altitude: 481, no_plants_sampled: nil, notes: "white/purple - Also:", team_members: "WG,DP,ID, RM", projection_id: 2193, is_seeds: true, is_cuttings: false)
Collection.create(id: -85, source_id: 5, date: "1/04/2017", source_description: "Champagne Gully", species_code: "SopMic", x: 1311553, y: 4996222, altitude: 481, no_plants_sampled: 1, notes: " - Also:DisTou, RosRub,CopPro", team_members: "WG,DP,ID, RM", projection_id: 2193, is_seeds: true, is_cuttings: false)
Collection.create(id: -84, source_id: 5, date: "1/04/2017", source_description: "Champagne Gully", species_code: "OleOdo", x: 1311540, y: 4996116, altitude: 530, no_plants_sampled: 1, notes: " - Also:DisTou, RosRub", team_members: "WG,DP,ID, RM", projection_id: 2193, is_seeds: true, is_cuttings: false)
Collection.create(id: -83, source_id: nil, date: "1/04/2017", source_description: "Champagne Gully", species_code: "CopPro", x: 1311546, y: 4996161, altitude: nil, no_plants_sampled: nil, notes: "yellow - Also:", team_members: "WG,DP,ID, RM", projection_id: 2193, is_seeds: true, is_cuttings: false)
Collection.create(id: -82, source_id: nil, date: "1/04/2017", source_description: "Champagne Gully", species_code: "CopPro", x: 1311558, y: 4996129, altitude: nil, no_plants_sampled: nil, notes: "white - Also:", team_members: "WG,DP,ID, RM", projection_id: 2193, is_seeds: true, is_cuttings: false)
Collection.create(id: -81, source_id: 5, date: "1/04/2017", source_description: "Champagne Gully", species_code: "CopPro", x: 1311540, y: 4996116, altitude: 530, no_plants_sampled: 2, notes: " - Also:", team_members: "WG,DP,ID, RM", projection_id: 2193, is_seeds: true, is_cuttings: false)
Collection.create(id: -80, source_id: 5, date: "1/04/2017", source_description: "Champagne Gully", species_code: "SopMic", x: 1311140, y: 4996198, altitude: 323, no_plants_sampled: 1, notes: "big - Also:", team_members: "WG,DP,ID, RM", projection_id: 2193, is_seeds: true, is_cuttings: false)
Collection.create(id: -79, source_id: 5, date: "1/04/2017", source_description: "Champagne Gully", species_code: "OleOdo", x: 1310967, y: 4996421, altitude: 273, no_plants_sampled: 3, notes: "damp gully - Also:", team_members: "WG,DP,ID, RM", projection_id: 2193, is_seeds: true, is_cuttings: false)
Collection.create(id: -78, source_id: 5, date: "8/04/2017", source_description: "Italian Creek", species_code: "CorCot", x: 1310244, y: 4997392, altitude: 282, no_plants_sampled: 1, notes: " - Also:MelAlp, MueCom, DisTou, RubSch, SopMic,CopPro,PimAri,CarCom.", team_members: "WG, CE, DP, AH", projection_id: 2193, is_seeds: true, is_cuttings: false)
Collection.create(id: -77, source_id: 5, date: "8/04/2017", source_description: "Italian Creek", species_code: "DisTou", x: 1310244, y: 4997392, altitude: 282, no_plants_sampled: 1, notes: " - Also:", team_members: "WG, CE, DP, AH", projection_id: 2193, is_seeds: true, is_cuttings: false)
Collection.create(id: -76, source_id: 5, date: "8/04/2017", source_description: "Italian Creek", species_code: "CorCot", x: 1310377, y: 4997433, altitude: 245, no_plants_sampled: 4, notes: " - Also:MyrDiv,CopPro,MelAlp, RubSch, RibUlv, PteEsc,AspFla, MueCom", team_members: "WG, CE, DP, AH", projection_id: 2193, is_seeds: true, is_cuttings: false)
Collection.create(id: -75, source_id: 5, date: "8/04/2017", source_description: "Italian Creek", species_code: "OleOdo", x: 1310624, y: 4997540, altitude: 290, no_plants_sampled: nil, notes: " - Also:HelLan, RubSch, CopPro, CorCot, RosRub, PteEsc, MueCom, (CarCom up slope)", team_members: "WG, CE, DP, AH", projection_id: 2193, is_seeds: true, is_cuttings: false)
Collection.create(id: -74, source_id: 5, date: "08/04/2017", source_description: "Italian Creek", species_code: "OleLin", x: 1310794, y: 4997564, altitude: 326, no_plants_sampled: 0, notes: "50+ OleLin up to 6m tall - Also:OleOdo,CopPro, RosRub, MueCom,", team_members: "WG, DP", projection_id: 2193, is_seeds: true, is_cuttings: false)
Collection.create(id: -73, source_id: 5, date: "08/04/2017", source_description: "Italian Creek", species_code: "AusRic", x: 1310794, y: 4997564, altitude: 326, no_plants_sampled: 1, notes: " - Also:", team_members: "WG, DP", projection_id: 2193, is_seeds: true, is_cuttings: false)
Collection.create(id: -72, source_id: 5, date: "08/04/2017", source_description: "Italian Creek", species_code: "VerSal", x: 1310211, y: 4997475, altitude: 213, no_plants_sampled: 1, notes: " - Also:RosRub,CopPro,SopMic,OzoVau", team_members: "WG, DP", projection_id: 2193, is_seeds: true, is_cuttings: false)
Collection.create(id: -71, source_id: nil, date: "15/04/2017", source_description: "Lilico Spur", species_code: "SopMic", x: 1314474, y: 4997408, altitude: 639, no_plants_sampled: 5, notes: " - Also:", team_members: "WG, DP, ID, Jo", projection_id: 2193, is_seeds: true, is_cuttings: false)
Collection.create(id: -70, source_id: nil, date: "15/04/2017", source_description: "Lilico Spur", species_code: "CorCot", x: nil, y: nil, altitude: nil, no_plants_sampled: nil, notes: " - Also:", team_members: "WG, DP, ID, Jo", projection_id: 2193, is_seeds: true, is_cuttings: false)


Collection.create(id: 1, source_id: 13,date: "31/03/2016", source_description: "WaikeriDownsWest", species_code: "OleOdo", x: 1311340.04420066, y: 4992613.80980273, altitude: nil, projection_id: 2193, no_plants_sampled: "many", team_members: "", notes: "Large-leaved plant (no seed) at 45.15577, 169.32695. Forests! Also 45.15270, 169.36663; 45 09 304, 169 19 706")
Collection.create(id: 2, source_id: 13,date: "31/03/2016", source_description: "WaikeriDownsWest", species_code: "VerPim", x: 1311172.59088157, y: 4993541.27053055, altitude: nil, projection_id: 2193, no_plants_sampled: "several", team_members: "", notes: "Also 45.15308, 169.32509; 45.15361, 169.32425")
Collection.create(id: 3, source_id: 13,date: "31/03/2016", source_description: "WaikeriDownsWest", species_code: "AciAur", x: 1311202.18055371, y: 4993531.48573322, altitude: nil, projection_id: 2193, no_plants_sampled: "one", team_members: "", notes: "")
Collection.create(id: 4, source_id: 13,date: "31/03/2016", source_description: "WaikeriDownsWest", species_code: "MueCom", x: 1311272.72272372, y: 4993348.79344066, altitude: nil, projection_id: 2193, no_plants_sampled: "two", team_members: "", notes: "Also 45.15427, 169.32213")
Collection.create(id: 5, source_id: 13,date: "31/03/2016", source_description: "WaikeriDownsWest", species_code: "CopPro", x: 1310891.74993009, y: 4993291.3660159, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "")
Collection.create(id: 6, source_id: 13,date: "31/03/2016", source_description: "WaikeriDownsWest", species_code: "MelAlp", x: 1311028.17009812, y: 4993374.39293689, altitude: nil, projection_id: 2193, no_plants_sampled: "several", team_members: "", notes: "")
Collection.create(id: 7, source_id: 13,date: "31/03/2016", source_description: "WaikeriDownsWest", species_code: "DisTou", x: 1311028.17009812, y: 4993374.39293689, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "")
Collection.create(id: 8, source_id: 1,date: "8/04/2016", source_description: "249 ChapmanRoad", species_code: "CopPro", x: 1311514.08268781, y: 4992891.12149732, altitude: nil, projection_id: 2193, no_plants_sampled: "one", team_members: "", notes: "")
Collection.create(id: 9, source_id: 14,date: "14/04/2016", source_description: "WaikerikeriValleyStn", species_code: "OleOdo", x: 1313796, y: 4996597, altitude: nil, projection_id: 2193, no_plants_sampled: "one", team_members: "", notes: "Waypoints NZTM (Matthew Sole)")
Collection.create(id: 10, source_id: 4,date: "14/04/2016", source_description: "ClydeBridge", species_code: "OzoVau", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "Sourced by DoC, provenance unknown")
Collection.create(id: 11, source_id: 14,date: "14/04/2016", source_description: "WaikerikeriValleyStn", species_code: "CorCot", x: 1313851, y: 4996527, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "Waypoints NZTM (Matthew Sole)")
Collection.create(id: 12, source_id: 1,date: "", source_description: "249 ChapmanRoad", species_code: "PitTen", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "")
Collection.create(id: 13, source_id: 14,date: "14/04/2016", source_description: "WaikerikeriValleyStn", species_code: "CopPro", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "")
Collection.create(id: 14, source_id: 14,date: "14/04/2016", source_description: "WaikerikeriValleyStn", species_code: "MelAlp", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "")
Collection.create(id: 15, source_id: 12,date: "31/03/2016", source_description: "TreestoneFar", species_code: "CarPet", x: 1310776.64685829, y: 4990686.78452351, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "")
Collection.create(id: 16, source_id: 13,date: "31/03/2016", source_description: "WaikeriDownsWest", species_code: "SopMic", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "")
Collection.create(id: 17, source_id: 8,date: "", source_description: "Robertson'sCreek", species_code: "CorAus", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "Poor fruits, drought? Threshed ")
Collection.create(id: 18, source_id: 7,date: "", source_description: "Pukerau", species_code: "OleHec", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "Cuttings from garden")
Collection.create(id: 19, source_id: 13,date: "25/05/2016", source_description: "WaikeriDownsWest", species_code: "SopMic", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "one", team_members: "", notes: "May flowering in forest")
Collection.create(id: 20, source_id: 9,date: "", source_description: "RoxburghGorge", species_code: "SopMic", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "several", team_members: "", notes: "get info from Ray")
Collection.create(id: 21, source_id: 15,date: "2/06/2016", source_description: "ChasmCreek", species_code: "MueAus", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "(DhanaPillai)", notes: "")
Collection.create(id: 22, source_id: 15,date: "3/06/2016", source_description: "ChasmCreek", species_code: "AciGla", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "(DhanaPillai)", notes: "")
Collection.create(id: 23, source_id: 15,date: "4/06/2016", source_description: "ChasmCreek", species_code: "DisTou", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "(DhanaPillai)", notes: "")
Collection.create(id: 24, source_id: 9,date: "10/06/2016", source_description: "RoxburghGorge", species_code: "PhoTen", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "(DhanaPillai)", notes: "")
Collection.create(id: 25, source_id: 13,date: "14/06/2016", source_description: "WaikeriDownsWest", species_code: "KunSer", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "Disturbed ground?")
Collection.create(id: 26, source_id: 9,date: "10/06/2016", source_description: "RoxburghGorge", species_code: "KunRob", x: 1311528.81757267, y: 4964207.2785353, altitude: nil, projection_id: 2193, no_plants_sampled: "5", team_members: "(DhanaPillai)", notes: "140m")
Collection.create(id: 27, source_id: 10,date: "13/06/2016", source_description: "GraveyardGully", species_code: "KunSer", x: 1317986.6470704, y: 4981574.77024727, altitude: nil, projection_id: 2193, no_plants_sampled: "3", team_members: "", notes: "290m")
Collection.create(id: 28, source_id: 9,date: "10/06/2016", source_description: "RoxburghGorge", species_code: "LepSco", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "1", team_members: "(DhanaPillai)", notes: "180m")
Collection.create(id: 29, source_id: 11,date: "10/06/2016", source_description: "ShingleCreek", species_code: "HelLan", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: ">20", team_members: "", notes: "140m")
Collection.create(id: 30, source_id: 15,date: "10/06/2016", source_description: "ChasmCreek", species_code: "SopMic", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: ">6", team_members: "(DhanaPillai)", notes: "530m")
Collection.create(id: 31, source_id: 13,date: "14/06/2016", source_description: "WaikeriDownsWest", species_code: "CarCom", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "290m")
Collection.create(id: 32, source_id: nil,date: "18/06/2016", source_description: "GermanHills", species_code: "CarPet", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "3", team_members: "(DhanaPillai)", notes: "")
Collection.create(id: 33, source_id: 10,date: "10/06/2016", source_description: "GraveyardGully", species_code: "SopMic", x: 1317854.98588212, y: 4981583.36412065, altitude: nil, projection_id: 2193, no_plants_sampled: "1", team_members: "(DhanaPillai)", notes: "Jun flowering")
Collection.create(id: 34, source_id: 11,date: "13/06/2016", source_description: "ShingleCreek", species_code: "SopMic", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "140m")
Collection.create(id: 35, source_id: 3,date: "", source_description: "Bendigo", species_code: "CorCot", x: 1313085.98206412, y: 5017072.96697446, altitude: nil, projection_id: 2193, no_plants_sampled: "7", team_members: "", notes: "600m")
Collection.create(id: 36, source_id: 6,date: "25/06/2016", source_description: "Omeo", species_code: "CorCot", x: 1305744, y: 4978725, altitude: nil, projection_id: 2193, no_plants_sampled: "7", team_members: "", notes: "917m")
Collection.create(id: 37, source_id: 6,date: "25/06/2016", source_description: "Omeo", species_code: "CopPro", x: 1305744, y: 4978725, altitude: nil, projection_id: 2193, no_plants_sampled: "6", team_members: "", notes: "917m")
Collection.create(id: 38, source_id: 6,date: "1/07/2016", source_description: "Omeo", species_code: "MelAlp", x: 1305918, y: 4978976, altitude: nil, projection_id: 2193, no_plants_sampled: "5", team_members: "", notes: "977m")
Collection.create(id: 39, source_id: 3,date: "", source_description: "Bendigo", species_code: "OleOdo", x: 1313771.78927677, y: 5017081.45827274, altitude: nil, projection_id: 2193, no_plants_sampled: "6", team_members: "", notes: "600m")
Collection.create(id: 40, source_id: 3,date: "", source_description: "Bendigo", species_code: "DisTou", x: 1313137.0557412, y: 5017097.52190768, altitude: nil, projection_id: 2193, no_plants_sampled: "6", team_members: "", notes: "600m")
Collection.create(id: 41, source_id: 6,date: "25/06/2016", source_description: "Omeo", species_code: "CarPet", x: 1305918, y: 4978976, altitude: nil, projection_id: 2193, no_plants_sampled: "3", team_members: "", notes: "977m")
Collection.create(id: 42, source_id: 6,date: "25/06/2016", source_description: "Omeo", species_code: "DisTou", x: 1305744, y: 4978725, altitude: nil, projection_id: 2193, no_plants_sampled: "9", team_members: "", notes: "917m")
Collection.create(id: 43, source_id: 3,date: "", source_description: "Bendigo", species_code: "KunSer", x: 1313771.78927677, y: 5017081.45827274, altitude: nil, projection_id: 2193, no_plants_sampled: "6", team_members: "", notes: "600m")
Collection.create(id: 44, source_id: 10,date: "", source_description: "GoatsHeadGully", species_code: "KunSer", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "HelenHillis", notes: "")
Collection.create(id: 45, source_id: nil,date: "28/08/2016", source_description: "Devils Creek", species_code: "OleAvi", x: 1307955, y: 5011297, altitude: nil, projection_id: 2193, no_plants_sampled: "1", team_members: "", notes: "")
Collection.create(id: 46, source_id: 15,date: "25/07/2016", source_description: "Blackstone Hill", species_code: "MelAlp", x: 1350392, y: 5015410, altitude: nil, projection_id: 2193, no_plants_sampled: "20+", team_members: "", notes: "")
Collection.create(id: 47, source_id: 10,date: "25/10/2016", source_description: "GraveyardGully", species_code: "PimAri", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "HelenHillis", notes: "")
Collection.create(id: 48, source_id: nil,date: "", source_description: "Cromwell Gorge", species_code: "SopMic", x: 1310264.027, y: 4990665, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "")
Collection.create(id: 49, source_id: nil,date: "", source_description: "SH8 Champagne", species_code: "SopMic", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "310/2")
Collection.create(id: 50, source_id: 13,date: "", source_description: "WaikeriDownsWest", species_code: "SopMic", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "Late")
Collection.create(id: 51, source_id: nil,date: "18/10/2016", source_description: "", species_code: "SopMic", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "(Bill and Tim)", notes: "Big")
Collection.create(id: 52, source_id: nil,date: "31/03/2016", source_description: "", species_code: "SopMic", x: 1310946.359, y: 4993383.456, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "(Bill, Inge, John)", notes: "very early flowering tree, seeds on ground")
Collection.create(id: 53, source_id: 13,date: "25/05/2016", source_description: "WaikeriDownsWest", species_code: "SopMic", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "May flowering")
Collection.create(id: 54, source_id: nil,date: "", source_description: "ex hills above Ida Valley", species_code: "SopMic", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "(Murray Kokich)", notes: "")
Collection.create(id: 55, source_id: nil,date: "", source_description: "behind Black Ridge", species_code: "SopMic", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "(Kevin Clarke)", notes: "seeds eaten in storage")
Collection.create(id: 56, source_id: 13,date: "14/06/2016", source_description: "WaikeriDownsWest", species_code: "CarCom", x: 1310422.623, y: 4992191.812, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "")
Collection.create(id: 57, source_id: 14,date: "14/04/2016", source_description: "WaikerikeriValleyStn", species_code: "CorCot", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "")
Collection.create(id: 58, source_id: 14,date: "14/04/2016", source_description: "WaikerikeriValleyStn", species_code: "CorCot", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "")
Collection.create(id: 59, source_id: 14,date: "14/04/2016", source_description: "WaikerikeriValleyStn", species_code: "CorCot", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "")
Collection.create(id: 60, source_id: 14,date: "14/04/2016", source_description: "WaikerikeriValleyStn", species_code: "CorCot", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "Equivalent with 011")
Collection.create(id: 61, source_id: 13,date: "31/03/2016", source_description: "WaikeriDownsWest", species_code: "OleOdo", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "Equivalent with 001")
Collection.create(id: 62, source_id: 12,date: "", source_description: "TreestoneFar", species_code: "PimAri", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "Equivalent with 023")
Collection.create(id: 63, source_id: 15,date: "4/06/2016", source_description: "ChasmCreek", species_code: "DisTou", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "4", team_members: "(DhanaPillai)", notes: "")
Collection.create(id: 64, source_id: nil,date: "14/06/2016", source_description: "", species_code: "MueCom", x: 1310438.567, y: 4992239.295, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "")
Collection.create(id: 65, source_id: nil,date: "", source_description: "", species_code: "CorCot", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "")
Collection.create(id: 66, source_id: 10,date: "13/06/2016", source_description: "GraveyardGully", species_code: "CorCot", x: 1318025.334, y: 4981494.678, altitude: nil, projection_id: 2193, no_plants_sampled: "3", team_members: "HH & DP", notes: "")
Collection.create(id: 67, source_id: 12,date: "", source_description: "TreestoneFar", species_code: "CarCom", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "")
Collection.create(id: 68, source_id: 12,date: "", source_description: "TreestoneFar", species_code: "CopPro", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "")
Collection.create(id: 69, source_id: nil,date: "", source_description: "Upper Clutha", species_code: "OleHec", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "")
Collection.create(id: 70, source_id: 10,date: "2/12/2016", source_description: "Piwakawaka Gorge", species_code: "CleQua", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "")
Collection.create(id: 71, source_id: 10,date: "2/12/2016", source_description: "", species_code: "OleLin", x: 1318692.494, y: 4979258.119, altitude: nil, projection_id: 2193, no_plants_sampled: "8+", team_members: "", notes: "")
Collection.create(id: 72, source_id: 10,date: "19/08/2016", source_description: "Piwakawaka Gorge", species_code: "VerSal", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "")
Collection.create(id: 73, source_id: 10,date: "", source_description: "Old Coach Road", species_code: "OleLin", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "")
Collection.create(id: 74, source_id: 10,date: "2/12/2016", source_description: "Piwakawaka Gorge", species_code: "CleQua", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: " ?last years seed")
Collection.create(id: 75, source_id: nil,date: "9/12/2016", source_description: "Wanaka area", species_code: "OleLin", x: 1319569.668, y: 4980739.706, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "")
Collection.create(id: 76, source_id: nil,date: "", source_description: "water race", species_code: "OleLin", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "1", team_members: "", notes: "")
Collection.create(id: 77, source_id: nil,date: "", source_description: "Wanaka area", species_code: "OleFra", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "")
Collection.create(id: 78, source_id: nil,date: "10/12/2016", source_description: "Frog Pond", species_code: "CleQua", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "")
Collection.create(id: 79, source_id: nil,date: "", source_description: "Wanaka area", species_code: "PlaReg", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "caterpillar present")
Collection.create(id: 80, source_id: 2,date: "7/01/2017", source_description: "Alex airport", species_code: "RaoAus", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "15+", team_members: "DP", notes: "")
Collection.create(id: 81, source_id: 2,date: "8/01/2017", source_description: "Alex airport", species_code: "RaoAus", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "10+", team_members: "DP", notes: "")
Collection.create(id: 82, source_id: nil,date: "9/02/2017", source_description: "Dairy Ck", species_code: "OleOdo", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "")
Collection.create(id: 83, source_id: 10,date: "8/03/2017", source_description: "Piwakawaka Gorge", species_code: "MyrDiv", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "")
Collection.create(id: 84, source_id: nil,date: "", source_description: "Wanaka area", species_code: "OleFim", x: nil, y: nil, altitude: nil, projection_id: 2193, no_plants_sampled: "", team_members: "", notes: "")


Seed.create(collection_id: 1, seed_code: "1.1", date_sown: "19/04/2016", is_active: true, notes: "Rubbed dried seeds through sieve to disaggregate and distribute evenly over soil")
Seed.create(collection_id: 2, seed_code: "2.1", date_sown: "19/04/2016", is_active: true, notes: "")
Seed.create(collection_id: 3, seed_code: "3.1", date_sown: "19/04/2016", is_active: true, notes: "Dried flower spikes with seeds inside pillow case for about a week. ")
Seed.create(collection_id: 4, seed_code: "4.1", date_sown: "19/04/2016", is_active: true, notes: "When dry, beat pillow case to release seeds. Winnowed away chaff from seeds")
Seed.create(collection_id: 5, seed_code: "5.1", date_sown: "21/04/2016", is_active: true, notes: "Soaked seeds in water 30min. (literature suggests ferment up to 7 days)Rub off fleshy berry, rinse in sieve, dry, winnow off  dried up light material")
Seed.create(collection_id: 6, seed_code: "6.1", date_sown: "21/04/2016", is_active: true, notes: "Soaked seeds in water 30min. (literature suggests ferment up to 7 days)Rub off fleshy berry, rinse in sieve, dry, winnow off  dried up light material")
Seed.create(collection_id: 7, seed_code: "7.1", date_sown: "21/04/2016", is_active: true, notes: "")
Seed.create(collection_id: 8, seed_code: "8.1", date_sown: "21/04/2016", is_active: true, notes: "")
Seed.create(collection_id: 9, seed_code: "9.1", date_sown: "21/04/2016", is_active: true, notes: "")
Seed.create(collection_id: 10, seed_code: "10.1", date_sown: "21/04/2016", is_active: true, notes: "Rubbed dried seeds through sieve to disaggregate and distribute evenly over soil")
Seed.create(collection_id: 11, seed_code: "11.1", date_sown: "21/04/2016", is_active: true, notes: "Soaked seeds in water 30min. (literature suggests ferment up to 7 days)Rub off fleshy berry, rinse in sieve, dry, winnow off  dried up light material")
Seed.create(collection_id: 12, seed_code: "12.1", date_sown: "24/04/2016", is_active: true, notes: "")
Seed.create(collection_id: 13, seed_code: "13.1", date_sown: "24/04/2016", is_active: true, notes: "")
Seed.create(collection_id: 14, seed_code: "14.1", date_sown: "24/04/2016", is_active: true, notes: "")
Seed.create(collection_id: 15, seed_code: "15.1", date_sown: "5/05/2016", is_active: true, notes: "")
Seed.create(collection_id: 16, seed_code: "16.1", date_sown: "5/05/2016", is_active: true, notes: "Testa cracked with pliers then soaked/rinsed four days")
Seed.create(collection_id: 17, seed_code: "17.1", date_sown: "26/05/2016", is_active: true, notes: "")
Seed.create(collection_id: 18, seed_code: "18.1", date_sown: "22/05/2016", is_active: true, notes: "")
Seed.create(collection_id: 19, seed_code: "19.1", date_sown: "9/06/2016", is_active: true, notes: "Hot water then soaked/rinsed four days")
Seed.create(collection_id: 20, seed_code: "20.1", date_sown: "16/06/2016", is_active: true, notes: "Ray - soak in Coca-Cola?")
Seed.create(collection_id: 21, seed_code: "21.1", date_sown: "16/06/2016", is_active: true, notes: "")
Seed.create(collection_id: 22, seed_code: "22.1", date_sown: "16/06/2016", is_active: true, notes: "")
Seed.create(collection_id: 23, seed_code: "23.1", date_sown: "16/06/2016", is_active: true, notes: "")
Seed.create(collection_id: 24, seed_code: "24.1", date_sown: "16/06/2016", is_active: true, notes: "")
Seed.create(collection_id: 25, seed_code: "25.1", date_sown: "16/06/2016", is_active: true, notes: "")
Seed.create(collection_id: 26, seed_code: "26.1", date_sown: "23/06/2016", is_active: true, notes: "")
Seed.create(collection_id: 27, seed_code: "27.1", date_sown: "23/06/2016", is_active: true, notes: "")
Seed.create(collection_id: 28, seed_code: "28.1", date_sown: "23/06/2016", is_active: true, notes: "")
Seed.create(collection_id: 29, seed_code: "29.1", date_sown: "23/06/2016", is_active: true, notes: "")
Seed.create(collection_id: 30, seed_code: "30.1", date_sown: "23/06/2016", is_active: true, notes: "")
Seed.create(collection_id: 31, seed_code: "31.1", date_sown: "23/06/2016", is_active: true, notes: "")
Seed.create(collection_id: 32, seed_code: "32.1", date_sown: "23/06/2016", is_active: true, notes: "")
Seed.create(collection_id: 33, seed_code: "33.1", date_sown: "30/06/2016", is_active: true, notes: "")
Seed.create(collection_id: 34, seed_code: "34.1", date_sown: "30/06/2016", is_active: true, notes: "")
Seed.create(collection_id: 35, seed_code: "35.1", date_sown: "14/07/2016", is_active: true, notes: "entire berries")
Seed.create(collection_id: 36, seed_code: "36.1", date_sown: "14/07/2016", is_active: true, notes: "entire berries")
Seed.create(collection_id: 37, seed_code: "37.1", date_sown: "14/07/2016", is_active: true, notes: "entire berries")
Seed.create(collection_id: 38, seed_code: "38.1", date_sown: "14/07/2016", is_active: true, notes: "entire berries")
Seed.create(collection_id: 39, seed_code: "39.1", date_sown: "14/07/2016", is_active: true, notes: "")
Seed.create(collection_id: 40, seed_code: "40.1", date_sown: "14/07/2016", is_active: true, notes: "crushed pods")
Seed.create(collection_id: 41, seed_code: "41.1", date_sown: "14/07/2016", is_active: true, notes: "Boiling water over pods 30min")
Seed.create(collection_id: 42, seed_code: "42.1", date_sown: "14/07/2016", is_active: true, notes: "crushed pods")
Seed.create(collection_id: 43, seed_code: "43.1", date_sown: "14/07/2016", is_active: true, notes: "")
Seed.create(collection_id: 44, seed_code: "44.1", date_sown: "24/07/2016", is_active: true, notes: "Fruits/capsules directly")
Seed.create(collection_id: 45, seed_code: "45.1", date_sown: "1/09/2016", is_active: true, notes: "")
Seed.create(collection_id: 46, seed_code: "46.1", date_sown: "15/09/2016", is_active: true, notes: "")
Seed.create(collection_id: 47, seed_code: "47.1", date_sown: "27/01/2016", is_active: true, notes: "Fruits and flower remnant together")
Seed.create(collection_id: 48, seed_code: "48.1", date_sown: "17/11/2016", is_active: true, notes: "Clipped seeds and soaked in water for +24hr")
Seed.create(collection_id: 49, seed_code: "49.1", date_sown: "17/11/2016", is_active: true, notes: "Clipped seeds and soaked in water for +24hr")
Seed.create(collection_id: 50, seed_code: "50.1", date_sown: "17/11/2016", is_active: true, notes: "Clipped seeds and soaked in water for +24hr")
Seed.create(collection_id: 51, seed_code: "51.1", date_sown: "17/11/2016", is_active: true, notes: "Clipped seeds and soaked in water for +24hr")
Seed.create(collection_id: 52, seed_code: "52.1", date_sown: "17/11/2016", is_active: true, notes: "Clipped seeds and soaked in water for +24hr")
Seed.create(collection_id: 53, seed_code: "53.1", date_sown: "17/11/2016", is_active: true, notes: "Clipped seeds and soaked in water for +24hr")
Seed.create(collection_id: 54, seed_code: "54.1", date_sown: "17/11/2016", is_active: true, notes: "Clipped seeds and soaked in water for +24hr")
Seed.create(collection_id: 55, seed_code: "55.1", date_sown: "17/11/2016", is_active: true, notes: "Clipped seeds and soaked in water for <24hr")
Seed.create(collection_id: 56, seed_code: "56.1", date_sown: "17/11/2016", is_active: true, notes: "soaked seeds in hot water overnight")
Seed.create(collection_id: 57, seed_code: "57.1", date_sown: "17/11/2016", is_active: true, notes: "soaked seeds in vinegar")
Seed.create(collection_id: 58, seed_code: "58.1", date_sown: "17/11/2016", is_active: true, notes: "soaked seeds in water")
Seed.create(collection_id: 59, seed_code: "59.1", date_sown: "17/11/2016", is_active: true, notes: "soaked seeds in hot water")
Seed.create(collection_id: 60, seed_code: "60.1", date_sown: "17/11/2016", is_active: true, notes: "soaked seeds in water")
Seed.create(collection_id: 61, seed_code: "61.1", date_sown: "17/11/2016", is_active: true, notes: "")
Seed.create(collection_id: 62, seed_code: "62.1", date_sown: "17/11/2016", is_active: true, notes: "Seeds in various stages of maturity sown with flower remnants")
Seed.create(collection_id: 63, seed_code: "63.1", date_sown: "17/11/2016", is_active: true, notes: "")
Seed.create(collection_id: 64, seed_code: "64.1", date_sown: "17/11/2016", is_active: true, notes: "")
Seed.create(collection_id: 65, seed_code: "65.1", date_sown: "17/11/2016", is_active: true, notes: "seeds cleaned and stored over winter, clipped and soaked in cold water 48hrs")
Seed.create(collection_id: 66, seed_code: "66.1", date_sown: "24/11/2016", is_active: true, notes: "seeds in berries over winter (mouldy), cleaned in Nov, clipped and soaked in cold water 48hrs")
Seed.create(collection_id: 67, seed_code: "67.1", date_sown: "24/11/2016", is_active: true, notes: "tray of germinated seedlings from TSF")
Seed.create(collection_id: 68, seed_code: "68.1", date_sown: "24/11/2016", is_active: true, notes: "tray of germinated seedlings from TSF")
Seed.create(collection_id: 69, seed_code: "69.1", date_sown: "24/11/2016", is_active: true, notes: "Rubbed dried seeds through sieve to disaggregate and distribute evenly over soil")
Seed.create(collection_id: 70, seed_code: "70.1", date_sown: "8/12/2016", is_active: true, notes: "")
Seed.create(collection_id: 71, seed_code: "71.1", date_sown: "8/12/2016", is_active: true, notes: "")
Seed.create(collection_id: 72, seed_code: "72.1", date_sown: "8/12/2016", is_active: true, notes: "")
Seed.create(collection_id: 73, seed_code: "73.1", date_sown: "15/12/2016", is_active: true, notes: "")
Seed.create(collection_id: 74, seed_code: "74.1", date_sown: "15/12/2016", is_active: true, notes: "")
Seed.create(collection_id: 75, seed_code: "75.1", date_sown: "22/12/2016", is_active: true, notes: "")
Seed.create(collection_id: 76, seed_code: "76.1", date_sown: "5/01/2017", is_active: true, notes: "")
Seed.create(collection_id: 77, seed_code: "77.1", date_sown: "5/01/2017", is_active: true, notes: "")
Seed.create(collection_id: 78, seed_code: "78.1", date_sown: "5/01/2017", is_active: true, notes: "")
Seed.create(collection_id: 79, seed_code: "79.1", date_sown: "5/01/2017", is_active: true, notes: "tray1 planted green, tray 2 planted dry 12/1/17")
Seed.create(collection_id: 80, seed_code: "80.1", date_sown: "12/01/2017", is_active: true, notes: "")
Seed.create(collection_id: 81, seed_code: "81.1", date_sown: "12/01/2017", is_active: true, notes: "")
Seed.create(collection_id: 82, seed_code: "82.1", date_sown: "9/02/2017", is_active: true, notes: "")
Seed.create(collection_id: 83, seed_code: "83.1", date_sown: "9/03/2017", is_active: true, notes: "")
Seed.create(collection_id: 84, seed_code: "84.1", date_sown: "30/03/2017", is_active: true, notes: "")

Seedling.create(seed_code: "1.1", seedling_code: "1.1.1", date_potted: "27/10/2016", number_potted: 20, is_active: true)
Seedling.create(seed_code: "2.1", seedling_code: "2.1.1", date_potted: "6/10/2016", number_potted: 8, is_active: true)
Seedling.create(seed_code: "3.1", seedling_code: "3.1.1", date_potted: "27/10/2016", number_potted: 236, is_active: true)
Seedling.create(seed_code: "4.1", seedling_code: "4.1.1", date_potted: "10/11/2016", number_potted: 6, is_active: true)
Seedling.create(seed_code: "5.1", seedling_code: "5.1.1", date_potted: "6/10/2016", number_potted: 119, is_active: true)

Seedling.create(seed_code: "7.1", seedling_code: "7.1.1", date_potted: "15/12/2016", number_potted: 4, is_active: true)
Seedling.create(seed_code: "8.1", seedling_code: "8.1.1", date_potted: "13/10/2016", number_potted: 60, is_active: true)




Seedling.create(seed_code: "13.1", seedling_code: "13.1.1", date_potted: "10/11/2016", number_potted: 59, is_active: true)
Seedling.create(seed_code: "14.1", seedling_code: "14.1.1", date_potted: "10/11/2016", number_potted: 14, is_active: true)
Seedling.create(seed_code: "15.1", seedling_code: "15.1.1", date_potted: "6/10/2016", number_potted: 14, is_active: true)
Seedling.create(seed_code: "16.1", seedling_code: "16.1.1", date_potted: "17/11/2016", number_potted: 5, is_active: true)
Seedling.create(seed_code: "17.1", seedling_code: "17.1.1", date_potted: "20/10/2016", number_potted: 68, is_active: true)

Seedling.create(seed_code: "19.1", seedling_code: "19.1.1", date_potted: "17/11/2016", number_potted: 2, is_active: true)

Seedling.create(seed_code: "21.1", seedling_code: "21.1.1", date_potted: "20/10/2016", number_potted: 91, is_active: true)
Seedling.create(seed_code: "22.1", seedling_code: "22.1.1", date_potted: "3/11/2016", number_potted: 37, is_active: true)
Seedling.create(seed_code: "23.1", seedling_code: "23.1.1", date_potted: "5/01/2017", number_potted: 5, is_active: true)
Seedling.create(seed_code: "24.1", seedling_code: "24.1.1", date_potted: "20/10/2016", number_potted: 15, is_active: true)
Seedling.create(seed_code: "25.1", seedling_code: "25.1.1", date_potted: "10/11/2016", number_potted: 80, is_active: true)
Seedling.create(seed_code: "26.1", seedling_code: "26.1.1", date_potted: "15/12/2016", number_potted: 74, is_active: true)

Seedling.create(seed_code: "28.1", seedling_code: "28.1.1", date_potted: "3/11/2016", number_potted: 35, is_active: true)

Seedling.create(seed_code: "30.1", seedling_code: "30.1.1", date_potted: "10/11/2016", number_potted: 36, is_active: true)
Seedling.create(seed_code: "31.1", seedling_code: "31.1.1", date_potted: "6/10/2016", number_potted: 25, is_active: true)
Seedling.create(seed_code: "32.1", seedling_code: "32.1.1", date_potted: "24/11/2016", number_potted: 2, is_active: true)
Seedling.create(seed_code: "33.1", seedling_code: "33.1.1", date_potted: "", number_potted: 36, is_active: true)
Seedling.create(seed_code: "34.1", seedling_code: "34.1.1", date_potted: "10/11/2016", number_potted: 21, is_active: true)




Seedling.create(seed_code: "39.1", seedling_code: "39.1.1", date_potted: "6/10/2016", number_potted: 37, is_active: true)
Seedling.create(seed_code: "40.1", seedling_code: "40.1.1", date_potted: "24/11/2016", number_potted: 4, is_active: true)

Seedling.create(seed_code: "42.1", seedling_code: "42.1.1", date_potted: "15/12/2016", number_potted: 24, is_active: true)
Seedling.create(seed_code: "43.1", seedling_code: "43.1.1", date_potted: "15/12/2016", number_potted: 129, is_active: true)
Seedling.create(seed_code: "44.1", seedling_code: "44.1.1", date_potted: "8/12/2016", number_potted: 452, is_active: true)
Seedling.create(seed_code: "45.1", seedling_code: "45.1.1", date_potted: "15/12/2016", number_potted: 5, is_active: true)


Seedling.create(seed_code: "48.1", seedling_code: "48.1.1", date_potted: "17/02/2017", number_potted: 32, is_active: true)
Seedling.create(seed_code: "49.1", seedling_code: "49.1.1", date_potted: "", number_potted: 6, is_active: true)




Seedling.create(seed_code: "54.1", seedling_code: "54.1.1", date_potted: "23/03/2017", number_potted: 1, is_active: true)
Seedling.create(seed_code: "55.1", seedling_code: "55.1.1", date_potted: "17/02/2017", number_potted: 68, is_active: true)
Seedling.create(seed_code: "56.1", seedling_code: "56.1.1", date_potted: "23/03/2017", number_potted: 12, is_active: true)




Seedling.create(seed_code: "61.1", seedling_code: "61.1.1", date_potted: "23/03/2017", number_potted: 138, is_active: true)

Seedling.create(seed_code: "63.1", seedling_code: "63.1.1", date_potted: "23/03/2017", number_potted: 4)
Seedling.create(seed_code: "64.1", seedling_code: "64.1.1", date_potted: "23/03/2017", number_potted: 2, is_active: true)


Seedling.create(seed_code: "67.1", seedling_code: "67.1.1", date_potted: "24/11/2016", number_potted: 73, is_active: true)
Seedling.create(seed_code: "68.1", seedling_code: "68.1.1", date_potted: "24/11/2016", number_potted: 133, is_active: true)
Seedling.create(seed_code: "69.1", seedling_code: "69.1.1", date_potted: "23/03/2017", number_potted: 32, is_active: true)


Seedling.create(seed_code: "72.1", seedling_code: "72.1.1", date_potted: "12/01/2017", number_potted: 129, is_active: true)
Seedling.create(seed_code: "73.1", seedling_code: "73.1.1", date_potted: "23/03/2017", number_potted: 3, is_active: true)

Seedling.create(seed_code: "75.1", seedling_code: "75.1.1", date_potted: "9/03/2017", number_potted: 55, is_active: true)
Seedling.create(seed_code: "76.1", seedling_code: "76.1.1", date_potted: "23/03/2017", number_potted: 6, is_active: true)
Seedling.create(seed_code: "77.1", seedling_code: "77.1.1", date_potted: "23/03/2017", number_potted: 7, is_active: true)

Seedling.create(seed_code: "79.1", seedling_code: "79.1.1", date_potted: "9/03/2017", number_potted: 126, is_active: true)


